### ISSUE TITLE
微前端技术方案与落地

### ISSUE THREAD

**Issue by turkyden** [turkyden/turkyden#27]
## 方案 1

JS 沙箱隔离，使用闭包。

```mermaid
function foo(window) {
  console.log(window.document);
}
foo({
    document: {};
});
```

输出：

```text
 {}
```

CSS 隔离，采用 Webpack 打包时加入前缀

```css
// 宿主 host app
.next-btn {
    color: #eee;
}
// 子应用 sub app
.sub-app .next-btn {
    color: #eee;
}
```

```html
<sub-app>
    <!-- 子应用的节点 -->
</sub-app>
```

## 方案 2

![image](https://user-images.githubusercontent.com/24560160/113670855-33c41680-96e8-11eb-8a98-19bc870a4130.png)

- JS 隔离：使用 iframe
- CSS 隔离：使用 Shadow DOM

## 技术调研

[[1] m-app 一套基于  Shadow DOM 的微前端解决方案](https://github.com/ambit-tsai/m-app)
[[2] qinkun 一个基于 single-spa 的微前端的实现](https://github.com/umijs/qiankun)
